### ISSUE TITLE
Releases 1.1.0+ cause Terraform to crash

### ISSUE THREAD

**Issue by darend** [SumoLogic/sumologic-terraform-provider#88]
After upgrading our provider from 1.0.0 to 1.3.0 we encountered the error below. Testing using releases 1.1.0 and 1.2.0 and found the same result.

## Resources

```
resource "sumologic_collector" "cluster" {
  name        = "${var.cluster}"
  description = "Collector for the ${var.cluster} cluster"
}

resource "sumologic_http_source" "kubernetes" {
  name         = "kubernetes"
  collector_id = "${sumologic_collector.cluster.id}"
}
```

## TF output
```
> terraform plan -target module.sumologic

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.sumologic.sumologic_collector.cluster: Refreshing state... [id=135201152]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xd549db]
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0:
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: goroutine 23 [running]:
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/SumoLogic/sumologic-terraform-provider/sumologic.(*Client).Get(0xc0000cf1d0, 0xc0000ea2c0, 0x17, 0x1, 0x1, 0xc0000ea2c0, 0x17, 0x18, 0x1a468a0, 0x0)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/Development/terraform/sumologic-terraform-provider/sumologic/sumologic_client.go:186 +0x1cb
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/SumoLogic/sumologic-terraform-provider/sumologic.(*Client).GetCollector(0xc0000cf1d0, 0x80f0180, 0x80f0180, 0x0, 0x0)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/Development/terraform/sumologic-terraform-provider/sumologic/sumologic_collectors.go:9 +0xb8
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/SumoLogic/sumologic-terraform-provider/sumologic.resourceSumologicCollectorExists(0xc00026c770, 0x10063c0, 0xc0000cf1d0, 0xc00026c770, 0x0, 0x0)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/Development/terraform/sumologic-terraform-provider/sumologic/resource_sumologic_collector.go:162 +0x1b2
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003e6080, 0xc0006201e0, 0x10063c0, 0xc0000cf1d0, 0xc000358360, 0xc0006201e0, 0x0)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/schema/resource.go:432 +0x24d
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0003d0040, 0x1257520, 0xc00009a930, 0xc0001d2400, 0xc0003d0040, 0xc00009a930, 0xc000320bd0)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/plugin/grpc_provider.go:496 +0x334
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0xfd6980, 0xc0003d0040, 0x1257520, 0xc00009a930, 0xc0006200a0, 0x0, 0x1257520, 0xc00009a930, 0xc000322000, 0xbf)
2019-11-03T02:08:47.996Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/internal/tfplugin5/tfplugin5.pb.go:2983 +0x23e
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004e0480, 0x1262f20, 0xc000001500, 0xc000268000, 0xc00025e1b0, 0x1a1b5b0, 0x0, 0x0, 0x0)
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x470
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: google.golang.org/grpc.(*Server).handleStream(0xc0004e0480, 0x1262f20, 0xc000001500, 0xc000268000, 0x0)
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd25
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003e4190, 0xc0004e0480, 0x1262f20, 0xc000001500, 0xc000268000)
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-11-03T02:08:47.997Z [DEBUG] plugin.terraform-provider-sumologic_v1.3.0: 	/Users/rmiller/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
2019-11-03T02:08:47.998Z [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-sumologic_v1.3.0 pid=5918 error="exit status 2"
2019/11/03 02:08:47 [ERROR] module.sumologic: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/11/03 02:08:47 [ERROR] module.sumologic: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/03 02:08:47 [TRACE] [walkRefresh] Exiting eval tree: module.sumologic.sumologic_collector.cluster
2019/11/03 02:08:47 [TRACE] vertex "module.sumologic.sumologic_collector.cluster": visit complete
2019/11/03 02:08:47 [TRACE] vertex "module.sumologic.sumologic_collector.cluster": dynamic subgraph encountered errors
2019/11/03 02:08:47 [TRACE] vertex "module.sumologic.sumologic_collector.cluster": visit complete
2019/11/03 02:08:47 [TRACE] dag/walk: upstream of "module.sumologic.sumologic_http_source.kubernetes" errored, so skipping
2019/11/03 02:08:47 [TRACE] dag/walk: upstream of "module.sumologic.output.kubernetes_endpoint" errored, so skipping
2019/11/03 02:08:47 [TRACE] dag/walk: upstream of "module.sumologic.local_file.endpoints" errored, so skipping
2019/11/03 02:08:47 [TRACE] dag/walk: upstream of "provider.local (close)" errored, so skipping
2019/11/03 02:08:47 [TRACE] dag/walk: upstream of "provider.sumologic (close)" errored, so skipping
2019/11/03 02:08:48 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-11-03T02:08:48.000Z [DEBUG] plugin: plugin exited
2019-11-03T02:08:48.003Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=5883
2019-11-03T02:08:48.003Z [DEBUG] plugin: plugin exited
2019-11-03T02:08:48.006Z [DEBUG] plugin: plugin process exited: path=/conf/backing-services/.terraform/plugins/linux_amd64/terraform-provider-local_v1.4.0_x4 pid=5928
2019-11-03T02:08:48.006Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by rvmiller89** [comment]
Hi @darend  are you using `base_url` or `environment` authentication, and which value are you providing? It looks like the URL convention may have changed between v1.0.0 and v1.1.0: https://github.com/SumoLogic/sumologic-terraform-provider/compare/v1.0.0...v1.1.0#diff-b9c89d45ca840ad4dda60e0cf7fd5fa2R9

**Comment by darend** [comment]
> Hi @darend are you using base_url or environment authentication, and which value are you providing? It looks like the URL convention may have changed between v1.0.0 and v1.1.0:

We use environment variables with no parameters to the provider:

```
export SUMOLOGIC_ACCESSID=
export SUMOLOGIC_ACCESSKEY=
```

```
provider "sumologic" {
  version = "~> 1.3.0"
}
```

**Comment by hamstah** [comment]
Hi,
I have the same stack trace when trying to import a collector.
I'm using the latest version in master.

**Comment by hamstah** [comment]
So I tracked down the issue (I have a fix for the actual crash I will push in a PR), the endpoint is not set correctly in this new version.

The provider allows the initialisation of a sumologic client in NewClient with an empty environment value.
https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/provider.go#L62-L88

Notice line 75 we only check that the environment is empty if there is *already* an error. I believe this should be changed to ```if msg == "" {``` to catch the missing environment.

When the environment is empty and the base_url is empty the base_url is incorrectly set to an empty url.

https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/provider.go#L62-L88

Line 225 will set base_url to "" as the empty environment is not in the endpoints map, this should be changed to ensure the value is actually found in the map using the other lookup form `base_url, found = endpoints[client.Environment]` and then raising an error if found is false.

Then line 227 the parsing is being done without checking for errors, which would have flagged the issue too.

So it's a combination of behaviour change (requiring the environment), a bug in the check for its presence and then a few places without error checking (in the logic and also the reason of the crash).

@darend if you set the environment property on the provider to the one matching your sumo endpoint it should resolve your issue, see https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/sumologic_client.go#L25-L33 for the possible values.

**Comment by darend** [comment]
> @darend if you set the environment property on the provider to the one matching your sumo endpoint it should resolve your issue, see https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/sumologic_client.go#L25-L33 for the possible values.

Thanks @hamstah Adding `environment` addresses the issue.

Note that the usage doc indicates that `environment` is optional and defaults to `us-2` (which happens to be ours). See https://github.com/SumoLogic/sumologic-terraform-provider/blob/ddacb2319b171ecb95380b2072b15740a8ec4d4b/docs/sumologic-provider.md#argument-reference

**Comment by hamstah** [comment]
Interesting. I didn't see code related to defaulting to us-2 so it might
have been forgotten. Pretty easy to add, I will leave it to the sumo team
to fix.
